"""Initial migration

Revision ID: 7bbf0487f1c4
Revises: 
Create Date: 2024-11-03 22:37:23.073555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bbf0487f1c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('categories')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('movie_actor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['id'])
        batch_op.create_foreign_key(None, 'actor', ['actor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_actor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], name='category', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='questions_pkey')
    )
    # ### end Alembic commands ###
